### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by machalex** [lexik/LexikColissimoBundle#2]
../composer.phar require lexik/ws-colissimo
Using version ^1.0 for lexik/ws-colissimo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for lexik/ws-colissimo ^1.0 -> satisfiable by lexik/ws-colissimo[v1.0.0].
    - Conclusion: remove symfony/symfony v2.6.6
    - Conclusion: don't install symfony/symfony v2.6.6
    - lexik/ws-colissimo v1.0.0 requires symfony/validator >=2.1,<2.4 -> satisfiable by symfony/validator[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9].
    - don't install symfony/validator v2.2.0|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.1|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.10|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.11|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.2|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.3|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.4|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.5|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.6|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.7|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.8|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.2.9|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.0|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.1|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.10|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.11|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.12|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.13|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.14|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.15|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.16|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.17|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.18|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.19|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.2|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.20|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.21|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.22|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.23|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.24|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.25|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.26|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.27|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.28|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.29|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.3|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.30|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.31|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.32|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.33|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.34|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.35|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.36|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.4|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.5|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.6|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.7|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.8|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.3.9|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.0|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.1|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.10|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.11|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.12|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.13|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.2|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.3|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.4|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.5|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.6|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.7|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.8|don't install symfony/symfony v2.6.6
    - don't install symfony/validator v2.1.9|don't install symfony/symfony v2.6.6
    - Installation request for symfony/symfony == 2.6.6.0 -> satisfiable by symfony/symfony[v2.6.6].

**Comment by jeremy31** [comment]
Hello !
Write in composer .json : 
`    "symfony/validator": "2.3.9",
    "lexik/colissimo-bundle": "dev-master"`

**Comment by LyesBe** [comment]
Hi, I'm having an issue too, I did like jeremy31 said but I have this error now : 

[RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Undefined class constant 'API_VERSION_2_5_BC' in [PATH]/vendor/symfony/symfony/src
  /Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
  on line 755

**Comment by sdieunidou** [comment]
Hi,
What is your Symfony Version ?
