### ISSUE TITLE
Variables de configuration du config.yml

### ISSUE THREAD

**Issue by jeremy31** [lexik/LexikColissimoBundle#3]
Bonjour,

Je souhaite utiliser ce bundle pour plusieurs client mais sur la même plateforme.
Le problème, c'est que les variables contract_number et password doivent être renseignées dans le fichier config.yml.
Y-a-t'il une autre solution ?
Le mieux ce serait de faire comme pour les variables sender (you can overwrite the sender configured in you app/config.yml by passing an array as 3rd argument)

Merci

**Comment by sdieunidou** [comment]
Bonjour,
Le fonctionnement actuel du bundle ne prévoit pas cette possibilité.
Il n'a pas été update depuis un moment, si vous le souhaitez vous pouvez faire un pull request pour inclure cette fonctionnalité
